services:
  app:
    container_name: nexora
    image: m4rkus28/nexora:latest
    ports:
      - "8127:8000"
    env_file:
      - ./.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
